---
title: "Slideover"
subtitle: "Collapsible content overlays for Quarto Revealjs"
format: 
  revealjs:
    controls: true
    progress: false
    revealjs-plugins: 
      - slideover
---

# From the bottom, toggle manually

<br><br>Yup, that's it.

::: {.slideover--b}
Enable collapsible overlays in Quarto Revealjs presentations:

```code
format: 
  revealjs:
    revealjs-plugins: 
      - slideover
```

**Usage example**

```code
::: {.slideover--b}
Slideover text.
:::
```
:::


# From the bottom, auto-collapse

Toggles the slideover after five seconds.

::: {.slideover--b .auto-collapse-10}
Add `.auto-collapse` to the slideover:

```code
::: {.slideover--b .auto-collapse}
Slideover text that collapses after five seconds by default.
:::
```

Control the delay by suffixing seconds, like `.auto-collapse-10`:

```code
::: {.slideover--b .auto-collapse-10}
Slideover text that auto-collapses after 10 seconds.
:::
``` 

:::

# From the <br>right, toggle <br>manually

::: {.slideover--r}

This content slides over from the right side of the slide.

**Usage example**

```code
::: {.slideover--r}
Slideover text.
:::
```

:::

# One for the lefties.

::: {.slideover--l .auto-collapse-10}

Content can also slide over from the left side, sinisterly.

**Usage example**

```code
::: {.slideover--l}
Slideover text from the left.
:::
```

Yes, it's OK to be _sinister_. Take it from someone who is left-handed and was forced to write with his right hand.

> The idea that left is sinister comes from Latin, where _sinister_ simply meant "left" but gradually took on meanings like "unlucky" or "evil".

:::

# <br>And from the top, too.

::: {.slideover--t}

And, finally, content can also slide over from the top.

**Usage example**

```code
::: {.slideover--t}
Slideover text from the top.
:::
```

**Tips & tricks**

- Slideover provides only limited styling support.<br>For example, **bolding** and _italics_ are supported.
- For better styling, use [Tachyons Extension For Quarto](https://github.com/nareal/tachyons).
- Headings have special meaning in Quarto Revealjs presentations and are NOT supported inside slideovers.

:::

# Mad science, it works.

::: {.slideover--l .third}
Slides content over from the left, at at third of the size.
:::

::: {.slideover--b .quarters}
Slides content over from the bottom, at three-quarters of the size.

You can use the size adjustments on any slideover type.
:::

::: {.slideover--r .half}
Slides content over from the right, at half-size.
:::

::: {.slideover--t}
Slides content over from the top, with the default size at 40% width.

You can additionally include the following classes to decrease the default width of the slideovers, for modals with less content:

- `.quarters` — 3/4s or 75% of the default 40% width.
- `.half` — 1/2s or 50% of the default 40% width.
- `.third` — 1/3 or 33ish% of the default 40% width.
:::