name: Deploy Quarto Slideover Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build Slideover demo
        run: quarto render slideover.qmd --output-dir _site
      - name: Publish to GitHub Pages
        run: quarto publish gh-pages _site --no-render 