name: Deploy Quarto Slideover Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build site
        run: quarto render slideover.qmd
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site 